PANEL_NAME_POOL = [
    "Cosmology",
    "Cradle of Life",
    "Epoch of Re-ionization",
    "Extragalactic continuum",
    "Extragalactic Spectral line",
    "Gravitational Waves",
    "High Energy Cosmic Particles",
    "HI Galaxy science",
    "Magnetism",
    "Our Galaxy",
    "Pulsars",
    "Solar, Heliospheric and Ionospheric Physics",
    "Transients",
    "VLBI",
]


EXAMPLE_PROPOSAL = {
    "prsl_id": "prp-ska01-202204-02",
    "status": "draft",
    "cycle": "5000_2023",
    "info": {
        "title": "The Milky Way View",
        "proposal_type": {
            "main_type": "standard_proposal",
            "attributes": ["coordinated_proposal"],
        },
    },
}


REVIEWERS = [
    {
        "id": "c8f8f18a-3c70-4c39-8ed9-2d8d180d99a1",
        "jobTitle": "Prof.",
        "givenName": "Sofia",
        "surname": "Martinez",
        "displayName": "Sofia Martinez",
        "mail": "sofia.martinez@example.com",
        "officeLocation": "Main",
        "subExpertise": "Pulsar Timing",
    },
    {
        "id": "c8f8f18a-3c70-4c39-8ed9-2d8d180d99a2",
        "jobTitle": "Dr.",
        "givenName": "Liam",
        "surname": "O'Connor",
        "displayName": "Liam O'Connor",
        "mail": "liam.oconnor@example.com",
        "officeLocation": "Annex",
        "subExpertise": "Galaxy Evolution",
    },
    {
        "id": "c8f8f18a-3c70-4c39-8ed9-2d8d180d99a3",
        "jobTitle": "Dr.",
        "givenName": "Aisha",
        "surname": "Rahman",
        "displayName": "Aisha Rahman",
        "mail": "aisha.rahman@example.com",
        "officeLocation": "Lab 2",
        "subExpertise": "Radio Transients",
    },
    {
        "id": "c8f8f18a-3c70-4c39-8ed9-2d8d180d99a4",
        "jobTitle": "Prof.",
        "givenName": "Oliver",
        "surname": "Zhou",
        "displayName": "Oliver Zhou",
        "mail": "oliver.zhou@example.com",
        "officeLocation": "Main",
        "subExpertise": "Cosmic Magnetism",
    },
    {
        "id": "c8f8f18a-3c70-4c39-8ed9-2d8d180d99a5",
        "jobTitle": "Dr.",
        "givenName": "Chloe",
        "surname": "Dubois",
        "displayName": "Chloe Dubois",
        "mail": "chloe.dubois@example.com",
        "officeLocation": "Annex",
        "subExpertise": "HI Surveys",
    },
    {
        "id": "c8f8f18a-3c70-4c39-8ed9-2d8d180d99a6",
        "jobTitle": "Prof.",
        "givenName": "Raj",
        "surname": "Patel",
        "displayName": "Raj Patel",
        "mail": "raj.patel@example.com",
        "officeLocation": "Lab 1",
        "subExpertise": "Pulsar Timing",
    },
    {
        "id": "c8f8f18a-3c70-4c39-8ed9-2d8d180d99a7",
        "jobTitle": "Dr.",
        "givenName": "Amara",
        "surname": "Okafor",
        "displayName": "Amara Okafor",
        "mail": "amara.okafor@example.com",
        "officeLocation": "Main",
        "subExpertise": "Galaxy Evolution",
    },
    {
        "id": "c8f8f18a-3c70-4c39-8ed9-2d8d180d99a8",
        "jobTitle": "Prof.",
        "givenName": "Lucas",
        "surname": "Fischer",
        "displayName": "Lucas Fischer",
        "mail": "lucas.fischer@example.com",
        "officeLocation": "Lab 3",
        "subExpertise": "Radio Transients",
    },
    {
        "id": "c8f8f18a-3c70-4c39-8ed9-2d8d180d99a9",
        "jobTitle": "Dr.",
        "givenName": "Maya",
        "surname": "Kim",
        "displayName": "Maya Kim",
        "mail": "maya.kim@example.com",
        "officeLocation": "Main",
        "subExpertise": "HI Surveys",
    },
    {
        "id": "c8f8f18a-3c70-4c39-8ed9-2d8d180d99b1",
        "jobTitle": "Prof.",
        "givenName": "Ethan",
        "surname": "Nguyen",
        "displayName": "Ethan Nguyen",
        "mail": "ethan.nguyen@example.com",
        "officeLocation": "Annex",
        "subExpertise": "Cosmic Magnetism",
    },
]
