apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "ska-oso-services.resource-name" . }}-environment
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ska-oso-services.labels" . | indent 4 }}
data:
  LOG_LEVEL: {{ .Values.rest.logLevel }}
  API_PATH_PREFIX: {{ include "ska-oso-services.api-path" . | quote }}
  PIPELINE_TESTS_DEPLOYMENT: {{ .Values.pipeline_test_deployment | quote }}
  SKA_AUTH_AUDIENCE: {{ .Values.rest.authAudiences | join "," | quote }}
  SDP_SCRIPT_TMDATA: {{ .Values.global.oso.sdp_tmdata }}
  ENGINEERING_API_ENABLED: {{ .Values.rest.engineeringApiEnabled | quote }}
  USER_PORTAL_BASE_URL: {{ .Values.rest.userPortalBaseUrl | quote }}