apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "ska-oso-services.name" . }}-{{ .Values.rest.component }}-{{ .Release.Name }}-environment
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ska-oso-services.labels" . | indent 4 }}
    component:  {{ template "ska-oso-services.name" . }}
    domain: environment
    function: ska-oso-services-environment
    intent: production
data:
  LOG_LEVEL: {{ .Values.rest.logLevel }}
  API_PATH_PREFIX: {{ template "ska-oso-services.api-path" . }}
  PIPELINE_TESTS_DEPLOYMENT: {{ .Values.pipeline_test_deployment | quote }}
  SKA_AUTH_AUDIENCE: {{ .Values.rest.authAudiences | join "," | quote }}
  SDP_SCRIPT_TMDATA: {{ .Values.global.oso.sdp_tmdata }}
  ENGINEERING_API_ENABLED: {{ .Values.rest.engineeringApiEnabled | quote }}