{{ if .Values.rest.enabled }}
{{ if .Values.ingress.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "ska-oso-services.resource-name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ska-oso-services.labels" . | indent 4 }}
  annotations:
spec:
  rules:
    - host: {{ default "" .Values.ingress.host | quote }}
      http:
        paths:
          - path: {{ template "ska-oso-services.api-path" . }}
            pathType: Prefix
            backend:
              service:
                name: {{ template "ska-oso-services.resource-name" . }}
                port:
                  number: 5000
{{ end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "ska-oso-services.resource-name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ska-oso-services.labels" . | indent 4 }}
spec:
  ports:
  - port: 5000
  selector:
    app: {{ template "ska-oso-services.name" . }}
    release: {{ .Release.Name }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "ska-oso-services.resource-name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ska-oso-services.labels" . | indent 4 }}
spec:
  selector:
    matchLabels:
      app: {{ template "ska-oso-services.name" . }}
      release: {{ .Release.Name }}
  replicas: 1
  template:
    metadata:
      labels:
        {{- include "ska-oso-services.labels" . | indent 8 }}
    spec:
      containers:
      - name: oso-services
        image: "{{ .Values.rest.image.registry }}/{{ .Values.rest.image.image }}:{{$.Values.rest.image.tag | default $.Chart.AppVersion}}"
        imagePullPolicy: {{ .Values.rest.image.pullPolicy }}
        # Command set in the Docker image
        envFrom:
          - configMapRef:
              name: {{ template "ska-oso-services.resource-name" . }}-environment
          - configMapRef:
              name: {{ template "ska-oso-services.resource-name" . }}-environment-oda
          - secretRef: # This is after the configMapRef so if a user wants to get the PG_ environment variables all from a Secret they overwrite those from the ConfigMap
              {{ if $.Values.global.oda.postgres.secret.existingSecret.name }}
              name: {{ $.Values.global.oda.postgres.secret.existingSecret.name }}
              {{ else }}
              name: {{ template "ska-oso-services.oda-secret-name" $ }}
              {{- end }}
          - secretRef:
              {{ if $.Values.existingApplicationSecret.name }}
              name: {{ $.Values.existingApplicationSecret.name }}
              {{ else }}
              name: {{ template "ska-oso-services.application-secret-name" $ }}
              {{- end }}
        ports:
          - containerPort: 5000
        resources:
{{ toYaml .Values.rest.resources | indent 10 }}
  {{- with .Values.rest.nodeSelector }}
nodeSelector:
  {{ toYaml . | indent 8 }}
  {{- end }}
  {{- with .Values.rest.affinity }}
affinity:
  {{ toYaml . | indent 8 }}
  {{- end }}
  {{- with .Values.rest.tolerations }}
tolerations:
  {{ toYaml . | indent 8 }}
  {{- end }}
  {{ end }}
