{{- if .Values.vault.enabled }}
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: {{ template "ska-oso-services.application-secret-name" $ }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ska-oso-services.labels" . | indent 4 }}
spec:
  type: kv-v2
  mount: {{ $.Values.vault.mount }}
  path: {{ $.Values.vault.path }}
  destination:
    name: {{ template "ska-oso-services.application-secret-name" $ }}
    create: true
    overwrite: true
    transformation:
      excludeRaw: true
      excludes:
        - ".*"
      templates:
{{- if not .Values.s3ServiceAccount.enabled }}
{{- range .Values.vault.s3Secrets }}
            {{ .secretKey }}:
              text: '{{ printf "{{ get .Secrets %q }}" .targetEnv }}'
{{- end }}
{{- end }}
{{- range .Values.vault.secrets }}
            {{ .secretKey }}:
              text: '{{ printf "{{ get .Secrets %q }}" .targetEnv }}'
{{- end }}
{{- else }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "ska-oso-services.application-secret-name" $ }}
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
{{- range .Values.vault.s3Secrets }}
  {{ .secretKey }}: dummy-secret
{{- end }}
{{- range .Values.vault.secrets }}
  {{ .secretKey }}: dummy-secret
{{- end }}
{{- end }}