{{- if .Values.vault.enabled }}
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: {{ template "ska-oso-services.application-secret-name" $ }}
  namespace: {{ .Release.Namespace }}
spec:
  type: kv-v2
  mount: {{ $.Values.vault.mount }}
  path: {{ $.Values.vault.secretPath }}
  destination:
    name: {{ template "ska-oso-services.application-secret-name" $ }}
    create: true
    overwrite: true
    transformation:
      excludeRaw: true
      excludes:
        - ".*"
      templates:
{{- if not .Values.s3ServiceAccount.enabled }}
{{- range $envName, $vaultKey := .Values.vault.s3KeyMappings }}
            {{ $envName }}:
              text: '{{ printf "{{ get .Secrets %q }}" $vaultKey }}'
{{- end }}
{{- end }}
{{- range $envName, $vaultKey := .Values.vault.extraKeyMappings }}
            {{ $envName }}:
              text: '{{ printf "{{ get .Secrets %q }}" $vaultKey }}'
{{- end }}
{{- else }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "ska-oso-services.application-secret-name" $ }}
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
{{- range $envName, $_ := .Values.vault.keyMappings }}
  {{ $envName }}: dummy-secret
{{- end }}
{{- end }}