# .readthedocs.yaml
# Read the Docs configuration file.
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details
# https://about.readthedocs.com/blog/2026/04/uv-native-support/

# Required
version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.10"

python:
  install:
    - method: uv
      command: sync
      groups:
        - docs

# Build documentation in the docs/src/ directory with Sphinx
sphinx:
  configuration: docs/src/conf.py
  # Fail the docs build if there is a warning (eg if the autoimports are not configured)
  fail_on_warning: true

submodules:
  include: all