@startuml
top to bottom direction

title Detailed View: PHT

package "pht" as pht_pkg {

    package "api" <<Rectangle>> {

        package "panel_decision" <<Rectangle>> {
            object panel_decision_endpoints{
                + GET /panel-decisions/{decision_id}
                + GET /panel-decisions/list/{user_id}
                + POST /panel-decisions/
                + PUT /panel-decisions/{decision_id}
            }
        }
        
        package "panels_management" <<Rectangle>> {
            object panels_endpoints {
                + GET /panels//{panel_id}
                + GET /panels/list/{user_id}
                + POST /panels/
            }
        }
        
        package "prsls" <<Rectangle>> {
            object prsls_endpoints{
                + GET /prsls/{proposal_id}
                + GET /prsls/list/{user_id}
                + GET /prsls/osd/{cycle}
                + GET /prsls/reviews/{prsl_id}
                + GET /prsls/status/{status}
                + POST /prsls/batch
                + POST /prsls/create
                + POST /prsls/send-email/
                + POST /prsls/signed-url/delete/{filename}
                + POST /prsls/signed-url/download/{filename}
                + POST /prsls/signed-url/upload/{filename}
                + POST /prsls/validate
                + PUT /prsls/{proposal_id}
                + GET /prsls/member/{email}
            }
        }

        package "report" <<Rectangle>> {
            object report_endpoints{
                + GET /report/
            }
        }

        package "reviewers" <<Rectangle>> {
            object reviewers_endpoints{
                + GET /reviewers
            }
        }
        
        package "reviews" <<Rectangle>> {
            object reviews_endpoints{
                + GET /reviews/{review_id}
                + GET /reviews/list/{user_id}
                + POST /reviews
                + PUT /reviews/{review_id}
            }
        }
    }

    package "utils" <<Rectangle>> {
        package "email_helper" <<Rectangle>> {
            object email_helper_items {
                + render_email()
                + send_email_async()
            }
        }
        package "pht_handler" <<Rectangle>> {
            object pht_handler_items {
                + _get_array_class()
                + get_latest_entity_by_id()
                + join_proposals_panels_reviews_decisions()
                + transform_update_proposal()
            }
        }
        package "ms_graph" <<Rectangle>> {
            object ms_graph_items {
                + make_graph_call()
                + get_users_by_mail()
            }
        }
        package "s3_bucket" <<Rectangle>> {
            object s3_bucket_items {
                + create_presigned_url_delete_pdf()
                + create_presigned_url_download_pdf()
                + create_presigned_url_upload_pdf()
                + get_aws_client()
                + generate_presigned_url()
                + S3Config
                + S3Method (Enum)
            }
        }
        package "validation" <<Rectangle>> {
            class validate_duplicates <<function>>
            class validate_proposal <<function>>
        }
        
        package "constants" <<Rectangle>> {
        }
    }
    
    ' --- Relationships, return types only ---
    validate_proposal --> prsls_endpoints
    s3_bucket --> prsls_endpoints
    prsls_endpoints --> email_helper_items
    validate_duplicates --> panels_endpoints
    pht_handler_items --> prsls_endpoints 
    pht_handler_items --> report_endpoints
    constants --> reviewers_endpoints
    ms_graph_items --> prsls_endpoints 
    

}
@enduml