global:
  cluster_domain: techops.internal.skao.int

ska-db-oda-umbrella:
  enabled: true
  ska-db-oda:
    enabled: false # ska-oso-services doesn't need the ODA rest server
  postgresql:
    enabled: true
  pgadmin4:
    enabled: true
  ska-ser-skuid:
    skuid:
      enabled: true

