global:
  cluster_domain: techops.internal.skao.int

ska-oso-services:
  rest:
    oda:
      backendType: postgres

ska-db-oda-umbrella:
  ska-db-oda:
    rest:
      enabled: false # Disabled by default as ska-oso-services does not use the ska-db-oda REST server. Would be useful to enable for demos and testing.
  postgresql:
    enabled: true
  pgadmin4:
    enabled: true
  ska-ser-skuid:
    skuid:
      enabled: true

