{{- $name := include "ska-oso-services.name" .}}
{{- $secretName := printf "%s-%s-%s" $name "allsecrets" .Release.Name  -}}
{{- if .Values.vault.enabled }}
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: {{ $secretName }}
  namespace: {{ .Release.Namespace }}
spec:
  type: kv-v2
  mount: {{ $.Values.vault.mount }}
  path: {{ $.Values.vault.secretPath }}
  destination:
    name: {{ $secretName }}
    create: true
    overwrite: true
    excludeRaw: true
    includes:
    {{- range .Values.vault.secretKeys }}
      - {{ . }}
    {{- end }}
{{- else }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  # This list should match the keys that are in the secret in Vault (i.e. those in Values.vault.secretKeys)
  AWS_SERVER_PUBLIC_KEY: dummy_public_key
  AWS_SERVER_SECRET_KEY: dummy_secret_key
  SMTP_PASSWORD: dummy_smtp_password
{{- end }}